"use client"

import { useState } from "react"

export function DevToolsSection() {
  const [viewMode, setViewMode] = useState<"featured" | "bento" | "tree">("featured")

  return (
    <section className="px-4 md:px-6 py-16">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-8">
          <div>
            <h2 className="text-3xl md:text-4xl font-bold tracking-tight text-foreground">
              AI TOOLS FOR
              <br />
              X POST PERFORMANCE <span className="text-foreground/40 text-xl align-super">[+]</span>
            </h2>
            <p className="text-foreground/60 mt-2 text-sm">
              Built around how X&apos;s recommendation system actually works.
            </p>
          </div>
          
          <div className="flex items-center gap-6">
            <div className="flex items-center gap-2 text-sm">
              <span className="text-foreground/60">VIEW:</span>
              <button 
                onClick={() => setViewMode("featured")}
                className={`border px-2 py-0.5 text-xs font-mono ${viewMode === "featured" ? "border-[#fc6432] text-[#fc6432]" : "border-border text-foreground/60"}`}
              >
                [X] FEATURED
              </button>
            </div>
            <div className="flex items-center gap-2 text-sm">
              <span className="text-foreground/60">MODE:</span>
              <button 
                onClick={() => setViewMode("bento")}
                className={`border px-2 py-0.5 text-xs font-mono ${viewMode === "bento" ? "border-[#fc6432] text-[#fc6432]" : "border-border text-foreground/60"}`}
              >
                [X] BENTO
              </button>
              <button 
                onClick={() => setViewMode("tree")}
                className={`text-xs font-mono ${viewMode === "tree" ? "text-[#fc6432]" : "text-foreground/60"}`}
              >
                [ ] TREE
              </button>
            </div>
          </div>
        </div>

        {/* Tools Grid */}
        <div className="grid md:grid-cols-2 gap-4">
          {/* Post Scoring Card */}
          <div className="border border-border bg-card p-6">
            <div className="flex items-center gap-2 mb-4">
              <span className="text-xs border border-border px-2 py-0.5 font-mono text-foreground/60">
                AI ANALYSIS
              </span>
            </div>
            <h3 className="text-xl font-semibold mb-2 flex items-center gap-2 text-foreground">
              Post Performance Scoring
              <span>→</span>
            </h3>
            <p className="text-foreground/60 text-sm mb-6">
              Analyze a post using tiered scoring based on engagement signals, dwell time, and profile interactions — the same signals used by X&apos;s recommendation algorithm.
            </p>
            
            {/* Score Preview */}
            <div className="bg-[#1a1a1a] text-white p-4 font-mono text-xs">
              <div className="flex gap-2 mb-3">
                <span className="w-2 h-2 bg-red-500 rounded-full" />
                <span className="w-2 h-2 bg-yellow-500 rounded-full" />
                <span className="w-2 h-2 bg-green-500 rounded-full" />
              </div>
              <pre className="text-green-400">
{`{
  "tier": "Tier 1",
  "score": 87,
  "signals": {
    "engagement": 0.92,
    "dwell_time": 0.85
  }
}`}
              </pre>
            </div>
          </div>

          {/* AI Recommendations Card */}
          <div className="border border-border bg-card p-6">
            <div className="flex items-center gap-2 mb-4">
              <span className="text-xs border border-border px-2 py-0.5 font-mono text-foreground/60">
                GEMINI AI
              </span>
            </div>
            <h3 className="text-xl font-semibold mb-2 flex items-center gap-2 text-foreground">
              AI-Powered Improvement Suggestions
              <span>→</span>
            </h3>
            <p className="text-foreground/60 text-sm mb-6">
              Receive clear, actionable feedback and optimized example posts generated by Google Gemini to help increase reach, engagement, and follow-through.
            </p>
            
            {/* Platform Preview */}
            <div className="bg-[#f5f3f0] border border-border overflow-hidden">
              <div className="bg-[#e5e5e5] px-3 py-2 flex items-center gap-2">
                <div className="flex gap-1">
                  <span className="w-2 h-2 bg-red-400 rounded-full" />
                  <span className="w-2 h-2 bg-yellow-400 rounded-full" />
                  <span className="w-2 h-2 bg-green-400 rounded-full" />
                </div>
                <span className="text-xs text-foreground/60 font-mono ml-2">//XANAI · Analysis</span>
              </div>
              <div className="p-4">
                <div className="flex items-center justify-between mb-4">
                  <span className="font-semibold text-foreground">Suggestions</span>
                  <div className="flex gap-2">
                    <span className="text-xs border border-border px-2 py-0.5 text-foreground/60">Copy</span>
                    <span className="text-xs border border-border px-2 py-0.5 text-foreground/60">Regenerate</span>
                  </div>
                </div>
                <div className="border border-border p-3">
                  <div className="flex items-center gap-2">
                    <div className="w-6 h-6 bg-[#fc6432] rounded-full flex items-center justify-center text-white text-xs">AI</div>
                    <span className="font-medium text-sm text-foreground">Optimized Post</span>
                  </div>
                  <div className="flex gap-4 mt-2 text-xs text-foreground/60">
                    <span>+23% engagement</span>
                    <span>Better hook</span>
                    <span>Clear CTA</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

